# Simulation Configuration

# Simulation Parameters
simulation:
  name: "Ant Colony Simulation"
  version: "1.0.0"
  description: "Multi-agent ant colony simulation using active inference"

# Runtime Parameters
runtime:
  # Time Settings
  time:
    max_steps: 100000
    timestep: 0.1
    real_time_factor: 1.0
    
  # Execution
  execution:
    num_threads: 4
    gpu_enabled: false
    seed: 42
    deterministic: true

# Initialization
initialization:
  # World Setup
  world:
    random_seed: 42
    generate_terrain: true
    place_resources: true
    
  # Colony Setup
  colony:
    random_seed: 43
    place_nest: true
    distribute_agents: true

# Physics Engine
physics:
  # Engine Settings
  engine:
    type: "2D"
    collision_detection: true
    spatial_hash_size: 5.0
    
  # Parameters
  parameters:
    gravity: [0, 0]
    friction: 0.5
    restitution: 0.5
    
  # Constraints
  constraints:
    velocity_cap: 10.0
    force_cap: 100.0
    acceleration_cap: 20.0

# Integration
integration:
  # Methods
  method: "RK4"
  substeps: 2
  
  # Error Control
  error_tolerance: 1e-6
  max_iterations: 100
  
  # Stability
  stability_checks: true
  energy_conservation: true

# Active Inference Parameters
active_inference:
  # Global Parameters
  global:
    temperature: 1.0
    learning_rate: 0.1
    exploration_rate: 0.2
    
  # Hierarchical Settings
  hierarchical:
    levels: 3
    top_down_weight: 0.7
    bottom_up_weight: 0.3
    
  # Precision Settings
  precision:
    initial: 1.0
    learning_enabled: true
    adaptation_rate: 0.05

# Multi-Agent System
multi_agent:
  # Coordination
  coordination:
    enabled: true
    method: "decentralized"
    communication_range: 5.0
    
  # Synchronization
  synchronization:
    enabled: true
    update_frequency: 10
    sync_tolerance: 0.1
    
  # Load Balancing
  load_balancing:
    enabled: true
    method: "dynamic"
    threshold: 0.8

# Analysis Settings
analysis:
  # Data Collection
  data_collection:
    enabled: true
    frequency: 100
    detailed_logging: true
    
  # Metrics
  metrics:
    agent_level:
      - "position"
      - "velocity"
      - "energy"
      - "beliefs"
    colony_level:
      - "population"
      - "resources"
      - "efficiency"
      - "coordination"
    environment_level:
      - "resource_distribution"
      - "pheromone_maps"
      - "agent_density"
    
  # Statistics
  statistics:
    compute_mean: true
    compute_variance: true
    compute_correlations: true
    temporal_analysis: true

# Visualization
visualization:
  # Real-time Display
  realtime:
    enabled: true
    update_frequency: 10
    quality: "medium"
    
  # Recording
  recording:
    enabled: true
    format: "mp4"
    framerate: 30
    resolution: [1920, 1080]
    
  # Features
  features:
    show_agents: true
    show_pheromones: true
    show_resources: true
    show_stats: true
    
  # UI Elements
  ui:
    show_controls: true
    show_plots: true
    show_metrics: true
    interactive: true

# Data Management
data:
  # Storage
  storage:
    format: "hdf5"
    compression: true
    backup_frequency: 1000
    
  # Export
  export:
    enabled: true
    format: ["csv", "json"]
    frequency: 1000
    
  # Checkpointing
  checkpointing:
    enabled: true
    frequency: 5000
    keep_last: 5
    
  # Analysis Output
  analysis:
    save_plots: true
    save_metrics: true
    save_trajectories: true
    output_format: ["png", "pdf"]

# Performance Monitoring
performance:
  # Monitoring
  monitoring:
    enabled: true
    frequency: 100
    
  # Profiling
  profiling:
    enabled: true
    detailed: true
    
  # Optimization
  optimization:
    auto_tune: true
    target_fps: 30
    
  # Resource Usage
  resources:
    max_memory: "4GB"
    max_cpu_percent: 80
    gpu_memory_limit: "2GB"

# Debug Settings
debug:
  # Logging
  logging:
    level: "INFO"
    file: "logs/simulation.log"
    console_output: true
    
  # Validation
  validation:
    check_constraints: true
    verify_physics: true
    test_consistency: true
    
  # Development
  development:
    assertions_enabled: true
    extra_checks: true
    profile_code: true 